version: '2'
services:
  s3fastdfs-app:
    image: s3fastdfs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://s3fastdfs-mysql:3306/s3fastdfs?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://s3fastdfs-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://s3fastdfs-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  s3fastdfs-mysql:
    extends:
      file: mysql.yml
      service: s3fastdfs-mysql
  s3fastdfs-redis:
    extends:
      file: redis.yml
      service: s3fastdfs-redis
